-- Mirrors src/db/schema.ts exactly. Run via `npm run db:push`
-- (scripts/migrate.ts). Written by hand instead of generated by drizzle-kit
-- because drizzle-kit's CLI does not yet support the node:sqlite driver —
-- see the note in src/db/client.ts for why node:sqlite was chosen anyway
-- (zero native compilation, ships with Node itself).

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'CUSTOMER',
  created_at TEXT NOT NULL DEFAULT (current_timestamp)
);

CREATE TABLE IF NOT EXISTS vehicles (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  brand TEXT NOT NULL,
  type TEXT NOT NULL,
  seats INTEGER NOT NULL,
  luggage INTEGER NOT NULL,
  transmission TEXT NOT NULL,
  fuel_type TEXT NOT NULL,
  price_per_day REAL NOT NULL,
  rating REAL NOT NULL DEFAULT 4.5,
  review_count INTEGER NOT NULL DEFAULT 0,
  location TEXT NOT NULL,
  features_json TEXT NOT NULL DEFAULT '[]',
  image TEXT NOT NULL,
  available INTEGER NOT NULL DEFAULT 1,
  popular INTEGER NOT NULL DEFAULT 0,
  mileage TEXT NOT NULL DEFAULT 'Unlimited',
  description TEXT NOT NULL,
  stock_count INTEGER NOT NULL DEFAULT 1,
  low_stock_threshold INTEGER NOT NULL DEFAULT 3,
  inspection_expiry TEXT NOT NULL,
  warranty TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (current_timestamp),
  updated_at TEXT NOT NULL DEFAULT (current_timestamp)
);

CREATE TABLE IF NOT EXISTS bookings (
  id TEXT PRIMARY KEY,
  reference TEXT NOT NULL UNIQUE,
  vehicle_id TEXT NOT NULL,
  vehicle_name TEXT NOT NULL,
  vehicle_image TEXT NOT NULL,
  customer_name TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  pickup_location TEXT NOT NULL,
  dropoff_location TEXT NOT NULL,
  pickup_date TEXT NOT NULL,
  dropoff_date TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (current_timestamp),
  payment TEXT NOT NULL,
  status TEXT NOT NULL,
  amount REAL NOT NULL,
  source TEXT NOT NULL,
  lead_score INTEGER,
  lead_qualification TEXT,
  ai_note TEXT
);

CREATE TABLE IF NOT EXISTS campaigns (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  discount_pct INTEGER NOT NULL,
  vehicle_type TEXT NOT NULL,
  start_date TEXT NOT NULL,
  end_date TEXT NOT NULL,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (current_timestamp)
);
